# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    # default to default branch
    # target-branch: "main"
    open-pull-requests-limit: 3
    rebase-strategy: "disabled"
    ignore:
      # k8s dependencies will be updated manually along with tests
      - dependency-name: "k8s.io/*"
      - dependency-name: "sigs.k8s.io/*"
    reviewers:
      - "weizhoublue"
    labels:
      - release/none
      - pr/dependabot/gomod

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    # default to default branch
    # target-branch: "main"
    open-pull-requests-limit: 3
    rebase-strategy: "disabled"
    reviewers:
      - "weizhoublue"
    labels:
      - pr/dependabot/github-actions
      - release/none

  - package-ecosystem: "docker"
    directory: "/images"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    reviewers:
      - "weizhoublue"
    labels:
      - release/none
      - pr/dependabot/docker
