apiVersion: v2
name: spiderpool
home: "https://spidernet-io.github.io/spiderpool"
icon: https://raw.githubusercontent.com/spidernet-io/spiderpool/main/docs/images/spider.svg
# application or library
type: application
# no need to modify this version , CI will auto update it with /VERSION
version: 0.7.3
# This field is informational, and has no impact on chart version calculations .
# Leaving it unquoted can lead to parsing issues in some cases
# no need to modify this version , CI will auto update it with /VERSION
appVersion: "0.7.3"
kubeVersion: ">= 1.16.0-0"
description: ipam for kubernetes cni
sources:
  - "https://github.com/spidernet-io/spiderpool"
keywords:
  - spiderpool
  - networking
  - ipam
maintainers:
  - name: spidernet-io
    url: https://github.com/spidernet-io
