apiVersion: {{ include "capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ .Values.spiderpoolController.name | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "spiderpool.spiderpoolController.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.global.commonAnnotations }}
  annotations:
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.spiderpoolController.replicas }}
  selector:
    matchLabels:
      {{- include "spiderpool.spiderpoolController.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- if or .Values.spiderpoolController.podAnnotations .Values.global.commonAnnotations }}
      annotations:
        {{- if .Values.global.commonAnnotations }}
        {{- include "tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 8 }}
        {{- end }}
        {{- if .Values.spiderpoolController.podAnnotations }}
        {{- include "tplvalues.render" ( dict "value" .Values.spiderpoolController.podAnnotations "context" $ ) | nindent 8 }}
        {{- end }}
        {{- end }}
      labels:
        {{- include "spiderpool.spiderpoolController.selectorLabels" . | nindent 8 }}
        {{- if .Values.global.commonLabels }}
        {{- include "tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 8 }}
        {{- end }}
        {{- if .Values.spiderpoolController.podLabels }}
        {{- include "tplvalues.render" ( dict "value" .Values.spiderpoolController.podLabels "context" $ ) | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.spiderpoolController.image.imagePullSecrets }}
      imagePullSecrets:
      {{- with .Values.spiderpoolController.image.imagePullSecrets }}
      {{- toYaml . | trim | nindent 6 }}
      {{- end }}
      {{- end }}
      serviceAccountName: {{ .Values.spiderpoolController.name | trunc 63 | trimSuffix "-" }}
      priorityClassName: {{ default "system-node-critical" .Values.spiderpoolController.priorityClassName }}
      {{- if .Values.spiderpoolController.hostnetwork }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      {{- else }}
      hostNetwork: false
      dnsPolicy: ClusterFirst
      {{- end }}
      restartPolicy: Always
      {{- with .Values.spiderpoolController.tolerations }}
      tolerations:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.spiderpoolController.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.spiderpoolController.affinity }}
      affinity:
      {{- include "tplvalues.render" (dict "value" .Values.spiderpoolController.affinity "context" $) | nindent 6 }}
      {{- else }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    {{- include "spiderpool.spiderpoolController.selectorLabels" . | nindent 20 }}
      {{- end }}
      containers:
      - name: {{ .Values.spiderpoolController.name | trunc 63 | trimSuffix "-" }}
        image: {{ include "spiderpool.spiderpoolController.image" . | quote }}
        imagePullPolicy: {{ .Values.spiderpoolController.image.pullPolicy }}
        command:
        - {{ .Values.spiderpoolController.binName }}
        args:
        - daemon
        - --config-path=/tmp/spiderpool/config-map/conf.yml
        - --tls-server-cert=/etc/tls/tls.crt
        - --tls-server-key=/etc/tls/tls.key
        {{- with .Values.spiderpoolController.extraArgs }}
        {{- toYaml . | trim | nindent 8 }}
        {{- end }}
        ports:
        {{- if .Values.spiderpoolController.prometheus.enabled }}
        - name: metrics
          containerPort: {{ .Values.spiderpoolController.prometheus.port }}
          protocol: TCP
        {{- end }}
        - name: http
          containerPort: {{ .Values.spiderpoolController.httpPort }}
          protocol: TCP
        - name: webhook
          containerPort: {{ .Values.spiderpoolController.webhookPort }}
          protocol: TCP
        {{- if semverCompare ">=1.20-0" .Capabilities.KubeVersion.Version }}
        startupProbe:
          httpGet:
            host: {{ .Values.ipam.enableIPv4 | ternary "127.0.0.1" "::1" | quote }}
            path: /v1/runtime/startup
            port: {{ .Values.spiderpoolController.httpPort }}
            scheme: HTTP
          failureThreshold: {{ .Values.spiderpoolController.healthChecking.startupProbe.failureThreshold }}
          periodSeconds: {{ .Values.spiderpoolController.healthChecking.startupProbe.periodSeconds }}
          successThreshold: 1
        {{- end }}
        livenessProbe:
          httpGet:
            host: {{ .Values.ipam.enableIPv4 | ternary "127.0.0.1" "::1" | quote }}
            path: /v1/runtime/liveness
            port: {{ .Values.spiderpoolController.httpPort }}
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: {{ .Values.spiderpoolController.healthChecking.livenessProbe.periodSeconds }}
          successThreshold: 1
          failureThreshold: {{ .Values.spiderpoolController.healthChecking.livenessProbe.failureThreshold }}
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            host: {{ .Values.ipam.enableIPv4 | ternary "127.0.0.1" "::1" | quote }}
            path: /v1/runtime/readiness
            port: {{ .Values.spiderpoolController.httpPort }}
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: {{ .Values.spiderpoolController.healthChecking.readinessProbe.periodSeconds }}
          successThreshold: 1
          failureThreshold: {{ .Values.spiderpoolController.healthChecking.readinessProbe.failureThreshold }}
          timeoutSeconds: 1
        {{- with .Values.spiderpoolController.resources }}
        resources:
        {{- toYaml . | trim | nindent 10 }}
        {{- end }}
        lifecycle:
          preStop:
            exec:
              command:
                - {{ .Values.spiderpoolController.binName }}
                - shutdown
        env:
        - name: SPIDERPOOL_LOG_LEVEL
          value: {{ .Values.spiderpoolController.debug.logLevel | quote }}
        - name: SPIDERPOOL_ENABLED_METRIC
          value: {{ .Values.spiderpoolController.prometheus.enabled | quote }}
        - name: SPIDERPOOL_ENABLED_DEBUG_METRIC
          value: {{ .Values.spiderpoolController.prometheus.enabledDebugMetric | quote }}
        - name: SPIDERPOOL_METRIC_HTTP_PORT
          value: {{ .Values.spiderpoolController.prometheus.port | quote }}
        - name: SPIDERPOOL_GOPS_LISTEN_PORT
          value: {{ .Values.spiderpoolController.debug.gopsPort | quote }}
        - name: SPIDERPOOL_WEBHOOK_PORT
          value: {{ .Values.spiderpoolController.webhookPort | quote }}
        - name: SPIDERPOOL_HEALTH_PORT
          value: {{ .Values.spiderpoolController.httpPort | quote }}
        - name: SPIDERPOOL_GC_IP_ENABLED
          value: {{ .Values.ipam.gc.enabled | quote }}
        - name: SPIDERPOOL_GC_TERMINATING_POD_IP_ENABLED
          value: {{ .Values.ipam.gc.GcDeletingTimeOutPod.enabled | quote }}
        - name: SPIDERPOOL_GC_ADDITIONAL_GRACE_DELAY
          value: {{ .Values.ipam.gc.GcDeletingTimeOutPod.delay | quote }}
        - name: SPIDERPOOL_GC_DEFAULT_INTERVAL_DURATION
          value: {{ .Values.ipam.gc.gcAll.intervalInSecond | quote }}
        - name: SPIDERPOOL_MULTUS_CONFIG_ENABLED
          value: {{ .Values.multus.enableMultusConfig | quote }}
        - name: SPIDERPOOL_CNI_CONFIG_DIR
          value: {{ .Values.global.cniConfHostPath | quote }}
        - name: SPIDERPOOL_COORDINATOR_ENABLED
          value: {{ .Values.coordinator.enabled | quote }}
        - name: SPIDERPOOL_COORDINATOR_DEAFULT_NAME
          value: {{ .Values.coordinator.name | quote }}
        - name: SPIDERPOOL_CILIUM_CONFIGMAP_NAMESPACE_NAME
          value: {{ .Values.global.ciliumConfigMap | quote }}
        - name: SPIDERPOOL_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SPIDERPOOL_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        {{- with .Values.spiderpoolController.extraEnv }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.spiderpoolController.securityContext }}
        securityContext:
        {{- toYaml . | nindent 8 }}
        {{- end }}
        volumeMounts:
        - name: config-path
          mountPath: /tmp/spiderpool/config-map
          readOnly: true
        - name: cni-conf-dir
          mountPath: {{ .Values.global.cniConfHostPath }}
          readOnly: true
        - name: tls
          mountPath: /etc/tls
          readOnly: true
        {{- if .Values.spiderpoolController.extraVolumes }}
        {{- include "tplvalues.render" ( dict "value" .Values.spiderpoolController.extraVolumeMounts "context" $ ) | nindent 8 }}
        {{- end }}
      volumes:
      # To read the configuration from the config map
      - name: config-path
        configMap:
          name: {{ .Values.global.configName }}
      - name: cni-conf-dir
        hostPath:
          path:  {{ .Values.global.cniConfHostPath }}
          type: DirectoryOrCreate
      - name: tls
        projected:
          defaultMode: 0400
          sources:
          - secret:
              name: {{ .Values.spiderpoolController.tls.secretName | trunc 63 | trimSuffix "-" }}
              items:
                - key: tls.crt
                  path: tls.crt
                - key: tls.key
                  path: tls.key
      {{- if .Values.spiderpoolController.extraVolumeMounts }}
      {{- include "tplvalues.render" ( dict "value" .Values.spiderpoolController.extraVolumeMounts "context" $ ) | nindent 6 }}
      {{- end }}
