{{- if (eq .Values.spiderpoolController.tls.method "auto") }}
{{- $_ := include "generate-ca-certs" . }}
{{- end }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ .Values.spiderpoolController.name | trunc 63 | trimSuffix "-" }}
  annotations:
    {{- if (eq .Values.spiderpoolController.tls.method "certmanager") }}
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ .Values.spiderpoolController.name | trunc 63 | trimSuffix "-" }}-server-certs
    {{- end }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ .Values.spiderpoolController.name | trunc 63 | trimSuffix "-" }}
      namespace: {{ .Release.Namespace }}
      path: /mutate-spiderpool-spidernet-io-v2beta1-spidersubnet
      port: {{ .Values.spiderpoolController.webhookPort }}
    {{- if (eq .Values.spiderpoolController.tls.method "provided") }}
    caBundle: {{ .Values.spiderpoolController.tls.provided.tlsCa | required "missing spiderpoolController.tls.provided.tlsCa" }}
    {{- else if (eq .Values.spiderpoolController.tls.method "auto") }}
    caBundle: {{ .ca.Cert | b64enc }}
    {{- end }}
  failurePolicy: Fail
  name: spidersubnet.spiderpool.spidernet.io
  rules:
  - apiGroups:
    - spiderpool.spidernet.io
    apiVersions:
    - v2beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - spidersubnets
  sideEffects: None
{{- if .Values.multus.enableMultusConfig }}
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ .Values.spiderpoolController.name | trunc 63 | trimSuffix "-" }}
      namespace: {{ .Release.Namespace }}
      path: /mutate-spiderpool-spidernet-io-v2beta1-spidermultusconfig
      port: {{ .Values.spiderpoolController.webhookPort }}
    {{- if (eq .Values.spiderpoolController.tls.method "provided") }}
    caBundle: {{ .Values.spiderpoolController.tls.provided.tlsCa | required "missing spiderpoolController.tls.provided.tlsCa" }}
    {{- else if (eq .Values.spiderpoolController.tls.method "auto") }}
    caBundle: {{ .ca.Cert | b64enc }}
    {{- end }}
  failurePolicy: Fail
  name: spidermultusconfig.spiderpool.spidernet.io
  rules:
  - apiGroups:
    - spiderpool.spidernet.io
    apiVersions:
    - v2beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - spidermultusconfigs
  sideEffects: None
{{- end }}
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ .Values.spiderpoolController.name | trunc 63 | trimSuffix "-" }}
      namespace: {{ .Release.Namespace }}
      path: /mutate-spiderpool-spidernet-io-v2beta1-spiderippool
      port: {{ .Values.spiderpoolController.webhookPort }}
    {{- if (eq .Values.spiderpoolController.tls.method "provided") }}
    caBundle: {{ .Values.spiderpoolController.tls.provided.tlsCa | required "missing spiderpoolController.tls.provided.tlsCa" }}
    {{- else if (eq .Values.spiderpoolController.tls.method "auto") }}
    caBundle: {{ .ca.Cert | b64enc }}
    {{- end }}
  failurePolicy: Fail
  name: spiderippool.spiderpool.spidernet.io
  rules:
  - apiGroups:
    - spiderpool.spidernet.io
    apiVersions:
    - v2beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - spiderippools
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ .Values.spiderpoolController.name | trunc 63 | trimSuffix "-" }}
      namespace: {{ .Release.Namespace }}
      path: /mutate-spiderpool-spidernet-io-v2beta1-spiderreservedip
      port: {{ .Values.spiderpoolController.webhookPort }}
    {{- if (eq .Values.spiderpoolController.tls.method "provided") }}
    caBundle: {{ .Values.spiderpoolController.tls.provided.tlsCa | required "missing spiderpoolController.tls.provided.tlsCa" }}
    {{- else if (eq .Values.spiderpoolController.tls.method "auto") }}
    caBundle: {{ .ca.Cert | b64enc }}
    {{- end }}
  failurePolicy: Fail
  name: spiderreservedip.spiderpool.spidernet.io
  rules:
  - apiGroups:
    - spiderpool.spidernet.io
    apiVersions:
    - v2beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - spiderreservedips
  sideEffects: None
{{- if .Values.coordinator.enabled }}
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ .Values.spiderpoolController.name | trunc 63 | trimSuffix "-" }}
      namespace: {{ .Release.Namespace }}
      path: /mutate-spiderpool-spidernet-io-v2beta1-spidercoordinator
      port: {{ .Values.spiderpoolController.webhookPort }}
    {{- if (eq .Values.spiderpoolController.tls.method "provided") }}
    caBundle: {{ .Values.spiderpoolController.tls.provided.tlsCa | required "missing spiderpoolController.tls.provided.tlsCa" }}
    {{- else if (eq .Values.spiderpoolController.tls.method "auto") }}
    caBundle: {{ .ca.Cert | b64enc }}
    {{- end }}
  failurePolicy: Fail
  name: spidercoordinator.spiderpool.spidernet.io
  rules:
  - apiGroups:
    - spiderpool.spidernet.io
    apiVersions:
    - v2beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - spidercoordinators
  sideEffects: None
{{- end }}
{{- if .Values.spiderpoolController.podResourceInject.enabled }}
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ .Values.spiderpoolController.name | trunc 63 | trimSuffix "-" }}
      namespace: {{ .Release.Namespace }}
      path: /mutate--v1-pod
      port: {{ .Values.spiderpoolController.webhookPort }}
    {{- if (eq .Values.spiderpoolController.tls.method "provided") }}
    caBundle: {{ .Values.spiderpoolController.tls.provided.tlsCa | required "missing spiderpoolController.tls.provided.tlsCa" }}
    {{- else if (eq .Values.spiderpoolController.tls.method "auto") }}
    caBundle: {{ .ca.Cert | b64enc }}
    {{- end }}
  failurePolicy: Fail
  name: pods.spiderpool.spidernet.io
  {{- if or .Values.spiderpoolController.podResourceInject.namespacesExclude .Values.spiderpoolController.podResourceInject.namespacesInclude }}
  namespaceSelector:
    matchExpressions:
    {{- if .Values.spiderpoolController.podResourceInject.namespacesExclude }}
    - key: kubernetes.io/metadata.name
      operator: NotIn
      values: {{ toYaml .Values.spiderpoolController.podResourceInject.namespacesExclude | nindent 8 }}
    {{- end }}
    {{- if .Values.spiderpoolController.podResourceInject.namespacesInclude }}
    - key: kubernetes.io/metadata.name
      operator: In
      values: {{ toYaml .Values.spiderpoolController.podResourceInject.namespacesInclude | nindent 8 }}
    {{- end }}
  {{- end }}
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
  sideEffects: None
{{- end }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: {{ .Values.spiderpoolController.name | trunc 63 | trimSuffix "-" }}
  annotations:
    {{- if (eq .Values.spiderpoolController.tls.method "certmanager") }}
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ .Values.spiderpoolController.name | trunc 63 | trimSuffix "-" }}-server-certs
    {{- end }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ .Values.spiderpoolController.name | trunc 63 | trimSuffix "-" }}
      namespace: {{ .Release.Namespace }}
      path: /validate-spiderpool-spidernet-io-v2beta1-spidersubnet
      port: {{ .Values.spiderpoolController.webhookPort }}
    {{- if (eq .Values.spiderpoolController.tls.method "provided") }}
    caBundle: {{ .Values.spiderpoolController.tls.provided.tlsCa | required "missing spiderpoolController.tls.provided.tlsCa" }}
    {{- else if (eq .Values.spiderpoolController.tls.method "auto") }}
    caBundle: {{ .ca.Cert | b64enc }}
    {{- end }}
  failurePolicy: Fail
  name: spidersubnet.spiderpool.spidernet.io
  rules:
  - apiGroups:
    - spiderpool.spidernet.io
    apiVersions:
    - v2beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - spidersubnets
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ .Values.spiderpoolController.name | trunc 63 | trimSuffix "-" }}
      namespace: {{ .Release.Namespace }}
      path: /validate-spiderpool-spidernet-io-v2beta1-spiderippool
      port: {{ .Values.spiderpoolController.webhookPort }}
    {{- if (eq .Values.spiderpoolController.tls.method "provided") }}
    caBundle: {{ .Values.spiderpoolController.tls.provided.tlsCa | required "missing spiderpoolController.tls.provided.tlsCa" }}
    {{- else if (eq .Values.spiderpoolController.tls.method "auto") }}
    caBundle: {{ .ca.Cert | b64enc }}
    {{- end }}
  failurePolicy: Fail
  name: spiderippool.spiderpool.spidernet.io
  rules:
  - apiGroups:
    - spiderpool.spidernet.io
    apiVersions:
    - v2beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - spiderippools
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ .Values.spiderpoolController.name | trunc 63 | trimSuffix "-" }}
      namespace: {{ .Release.Namespace }}
      path: /validate-spiderpool-spidernet-io-v2beta1-spiderreservedip
      port: {{ .Values.spiderpoolController.webhookPort }}
    {{- if (eq .Values.spiderpoolController.tls.method "provided") }}
    caBundle: {{ .Values.spiderpoolController.tls.provided.tlsCa | required "missing spiderpoolController.tls.provided.tlsCa" }}
    {{- else if (eq .Values.spiderpoolController.tls.method "auto") }}
    caBundle: {{ .ca.Cert | b64enc }}
    {{- end }}
  failurePolicy: Fail
  name: spiderreservedip.spiderpool.spidernet.io
  rules:
  - apiGroups:
    - spiderpool.spidernet.io
    apiVersions:
    - v2beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - spiderreservedips
  sideEffects: None
{{- if .Values.coordinator.enabled }}
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ .Values.spiderpoolController.name | trunc 63 | trimSuffix "-" }}
      namespace: {{ .Release.Namespace }}
      path: /validate-spiderpool-spidernet-io-v2beta1-spidercoordinator
      port: {{ .Values.spiderpoolController.webhookPort }}
    {{- if (eq .Values.spiderpoolController.tls.method "provided") }}
    caBundle: {{ .Values.spiderpoolController.tls.provided.tlsCa | required "missing spiderpoolController.tls.provided.tlsCa" }}
    {{- else if (eq .Values.spiderpoolController.tls.method "auto") }}
    caBundle: {{ .ca.Cert | b64enc }}
    {{- end }}
  failurePolicy: Fail
  name: spidercoordinator.spiderpool.spidernet.io
  rules:
  - apiGroups:
    - spiderpool.spidernet.io
    apiVersions:
    - v2beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - spidercoordinators
  sideEffects: None
{{- end }}
{{- if .Values.multus.enableMultusConfig }}
- admissionReviewVersions:
    - v1
  clientConfig:
    service:
      name: {{ .Values.spiderpoolController.name | trunc 63 | trimSuffix "-" }}
      namespace: {{ .Release.Namespace }}
      path: /validate-spiderpool-spidernet-io-v2beta1-spidermultusconfig
      port: {{ .Values.spiderpoolController.webhookPort }}
    {{- if (eq .Values.spiderpoolController.tls.method "provided") }}
    caBundle: {{ .Values.spiderpoolController.tls.provided.tlsCa | required "missing spiderpoolController.tls.provided.tlsCa" }}
    {{- else if (eq .Values.spiderpoolController.tls.method "auto") }}
    caBundle: {{ .ca.Cert | b64enc }}
    {{- end }}
  failurePolicy: Fail
  name: spidermultusconfig.spiderpool.spidernet.io
  rules:
    - apiGroups:
        - spiderpool.spidernet.io
      apiVersions:
        - v2beta1
      operations:
        - CREATE
        - UPDATE
      resources:
        - spidermultusconfigs
  sideEffects: None
{{- end }}
{{- if eq .Values.spiderpoolController.tls.method "certmanager" -}}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.spiderpoolController.name | trunc 63 | trimSuffix "-" }}-server-certs
  namespace: {{ .Release.Namespace }}
spec:
  issuerRef:
    name: {{ .Values.spiderpoolController.tls.certmanager.issuerName | trunc 63 | trimSuffix "-" }}
  secretName: {{ .Values.spiderpoolController.tls.secretName | trunc 63 | trimSuffix "-" }}
  commonName: {{ .Values.spiderpoolController.name | trunc 63 | trimSuffix "-" }}.{{ .Release.Namespace }}.svc
  dnsNames:
    - {{ .Values.spiderpoolController.name | trunc 63 | trimSuffix "-" }}
    - {{ .Values.spiderpoolController.name | trunc 63 | trimSuffix "-" }}.{{ .Release.Namespace }}
    - {{ .Values.spiderpoolController.name | trunc 63 | trimSuffix "-" }}.{{ .Release.Namespace }}.svc
    - {{ .Values.spiderpoolController.name | trunc 63 | trimSuffix "-" }}.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDnsDomain }}
  {{- range $dns := .Values.spiderpoolController.tls.certmanager.extraDnsNames }}
  - {{ $dns | quote }}
  {{- end }}
  {{- if .Values.spiderpoolController.tls.certmanager.extraIPAddresses }}
  ipAddresses:
  {{- range $ip := .Values.spiderpoolController.tls.certmanager.extraIPAddresses }}
  - {{ $ip | quote }}
  {{- end }}
  {{- end }}
  duration: {{ printf "%dh" (mul .Values.spiderpoolController.tls.certmanager.certValidityDuration 24) }}
{{- end }}
{{- if (eq .Values.spiderpoolController.tls.method "provided") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.spiderpoolController.tls.secretName | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  ca.crt:  {{ .Values.spiderpoolController.tls.provided.tlsCa | required "missing spiderpoolController.tls.provided.tlsCa" }}
  tls.crt: {{ .Values.spiderpoolController.tls.provided.tlsCert | required "missing spiderpoolController.tls.provided.tlsCert" }}
  tls.key: {{ .Values.spiderpoolController.tls.provided.tlsKey  | required "missing spiderpoolController.tls.provided.tlsKey"  }}
{{- end }}
{{- if eq .Values.spiderpoolController.tls.method "auto" }}
---
{{- $cn := printf "spidernet.io" }}
{{- $ip := .Values.spiderpoolController.tls.auto.extraIpAddresses }}
{{- $dns1 := printf "%s.%s" .Values.spiderpoolController.name .Release.Namespace }}
{{- $dns2 := printf "%s.%s.svc" .Values.spiderpoolController.name .Release.Namespace }}
{{- $dns3 := printf "%s.%s.svc.%s" .Values.spiderpoolController.name .Release.Namespace .Values.global.clusterDnsDomain }}
{{- $dns := prepend .Values.spiderpoolController.tls.auto.extraDnsNames $dns1 }}
{{- $dns = prepend $dns $dns2 }}
{{- $dns = prepend $dns $dns3 }}
{{- $dns = prepend $dns $cn }}
{{- $cert := genSignedCert $cn $ip $dns (.Values.spiderpoolController.tls.auto.certExpiration | int) .ca }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.spiderpoolController.tls.secretName | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  ca.crt:  {{ .ca.Cert | b64enc }}
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key  | b64enc }}
{{- end }}