---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: {{ .Values.spiderpoolController.name | trunc 63 | trimSuffix "-" }}
  annotations:
    {{- if (eq .Values.spiderpoolController.tls.method "certmanager") }}
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ .Values.spiderpoolController.name | trunc 63 | trimSuffix "-" }}-server-certs
    {{- end }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ .Values.spiderpoolController.name | trunc 63 | trimSuffix "-" }}
      namespace: {{ .Release.Namespace }}
      path: /mutate-spiderpool-spidernet-io-v1-spiderippool
      port: {{ .Values.spiderpoolController.webhookPort }}
    {{- if (eq .Values.spiderpoolController.tls.method "provided") }}
    caBundle: {{ .Values.spiderpoolController.tls.provided.tlsCa | required "missing spiderpoolController.tls.provided.tlsCa" }}
    {{- end }}
  failurePolicy: Fail
  name: spiderippool.spiderpool.spidernet.io
  rules:
  - apiGroups:
    - spiderpool.spidernet.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - spiderippools
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ .Values.spiderpoolController.name | trunc 63 | trimSuffix "-" }}
      namespace: {{ .Release.Namespace }}
      path: /mutate-spiderpool-spidernet-io-v1-spiderreservedip
      port: {{ .Values.spiderpoolController.webhookPort }}
    {{- if (eq .Values.spiderpoolController.tls.method "provided") }}
    caBundle: {{ .Values.spiderpoolController.tls.provided.tlsCa | required "missing spiderpoolController.tls.provided.tlsCa" }}
    {{- end }}
  failurePolicy: Fail
  name: spiderreservedip.spiderpool.spidernet.io
  rules:
  - apiGroups:
    - spiderpool.spidernet.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - spiderreservedips
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: {{ .Values.spiderpoolController.name | trunc 63 | trimSuffix "-" }}
  annotations:
    "helm.sh/hook": post-install
    {{- if (eq .Values.spiderpoolController.tls.method "certmanager") }}
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ .Values.spiderpoolController.name | trunc 63 | trimSuffix "-" }}-server-certs
    {{- end }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ .Values.spiderpoolController.name | trunc 63 | trimSuffix "-" }}
      namespace: {{ .Release.Namespace }}
      path: /validate-spiderpool-spidernet-io-v1-spiderippool
      port: {{ .Values.spiderpoolController.webhookPort }}
    {{- if (eq .Values.spiderpoolController.tls.method "provided") }}
    caBundle: {{ .Values.spiderpoolController.tls.provided.tlsCa | required "missing spiderpoolController.tls.provided.tlsCa" }}
    {{- end }}
  failurePolicy: Fail
  name: spiderippool.spiderpool.spidernet.io
  rules:
  - apiGroups:
    - spiderpool.spidernet.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - spiderippools
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ .Values.spiderpoolController.name | trunc 63 | trimSuffix "-" }}
      namespace: {{ .Release.Namespace }}
      path: /validate-spiderpool-spidernet-io-v1-spiderreservedip
      port: {{ .Values.spiderpoolController.webhookPort }}
    {{- if (eq .Values.spiderpoolController.tls.method "provided") }}
    caBundle: {{ .Values.spiderpoolController.tls.provided.tlsCa | required "missing spiderpoolController.tls.provided.tlsCa" }}
    {{- end }}
  failurePolicy: Fail
  name: spiderreservedip.spiderpool.spidernet.io
  rules:
  - apiGroups:
    - spiderpool.spidernet.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - spiderreservedips
  sideEffects: None