---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: {{ .Values.spiderpoolController.name | trunc 63 | trimSuffix "-" }}
  {{- if (eq .Values.spiderpoolController.tls.method "certmanager") }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ .Values.spiderpoolController.name | trunc 63 | trimSuffix "-" }}-server-certs
  {{- end }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ .Values.spiderpoolController.name | trunc 63 | trimSuffix "-" }}
      namespace: {{ .Release.Namespace }}
      path: /mutate-spiderpool-spidernet-io-v1-ippool
      port: {{ .Values.spiderpoolController.webhookPort }}
    {{- if (eq .Values.spiderpoolController.tls.method "provided") }}
    caBundle: {{ .Values.spiderpoolController.tls.server.ca | required "missing spiderpoolController.tls.server.ca" }}
    {{- end }}
  failurePolicy: Fail
  name: spiderpool.spidernet.io
  rules:
  - apiGroups:
    - spiderpool.spidernet.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ippools
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: {{ .Values.spiderpoolController.name | trunc 63 | trimSuffix "-" }}
  {{- if (eq .Values.spiderpoolController.tls.method "certmanager") }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ .Values.spiderpoolController.name | trunc 63 | trimSuffix "-" }}-server-certs
  {{- end }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ .Values.spiderpoolController.name | trunc 63 | trimSuffix "-" }}
      namespace: {{ .Release.Namespace }}
      path: /validate-spiderpool-spidernet-io-v1-ippool
      port: {{ .Values.spiderpoolController.webhookPort }}
    {{- if (eq .Values.spiderpoolController.tls.method "provided") }}
    caBundle: {{ .Values.spiderpoolController.tls.server.ca | required "missing spiderpoolController.tls.server.ca" }}
    {{- end }}
  failurePolicy: Fail
  name: spiderpool.spidernet.io
  rules:
  - apiGroups:
    - spiderpool.spidernet.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - ippools
  sideEffects: None
