swagger: "2.0"
info:
  description: Spiderpool Agent
  title: Spiderpool-Agent API
  version: v1
x-schemes:
  - unix
basePath: "/v1"
produces:
  - application/json
consumes:
  - application/json
paths:
  "/ipam/healthy":
    get:
      summary: Get health of spiderpool daemon
      description: |
        Check spiderpool daemonset health to make sure whether it's ready
        for CNI plugin usage
      tags:
        - connectivity
      responses:
        "200":
          description: Success
        "500":
          description: Failed
  "/ipam/ip":
    post:
      summary: Get ip from spiderpool daemon
      description: |
        Send a request to daemonset to ask for an ip assignment
      tags:
        - daemonset
      parameters:
        - name: ipam-add-args
          in: body
          required: true
          schema:
            $ref: "#/definitions/IpamAddArgs"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/IpamAddResponse"
        '500':
          description: Allocation failure
          x-go-name: Failure
          schema:
            $ref: "#/definitions/Error"
    delete:
      summary: Delete ip from spiderpool daemon
      description: |
        Send a request to daemonset to ask for an ip deleting
      tags:
        - daemonset
      parameters:
        - name: ipam-del-args
          in: body
          required: true
          schema:
            $ref: "#/definitions/IpamDelArgs"
      responses:
        "200":
          description: Success
        '500':
          description: Addresses release failure
          x-go-name: Failure
          schema:
            $ref: "#/definitions/Error"
  "/ipam/ips":
    post:
      summary: Assign multiple ip as a batch
      description: |
        Assign multiple ip for a pod, case for spiderflat compent
      tags:
        - daemonset
      responses:
        "200":
          description: Success
        "500":
          description: Allocation failure
          x-go-name: Failure
          schema:
            $ref: "#/definitions/Error"
    delete:
      summary: Delete multiple ip as a batch
      description: |
        Delete multiple ip for a pod, case for spiderflat compent
      tags:
        - daemonset
      responses:
        "200":
          description: Success
        '500':
          description: Addresses release failure
          x-go-name: Failure
          schema:
            $ref: "#/definitions/Error"
  "/workloadendpoint":
    get:
      summary: Get workloadendpoint status
      description: |
        Get workloadendpoint details for spiderflat use
      tags:
        - daemonset
      responses:
        "200":
          description: Success
        "500":
          description: Get workloadendpoint failure
  "/coordinator/config":
    get:
      summary: Get coordinator config
      description: |
        Send a request to daemonset to get coordinator config
      tags:
        - daemonset
      parameters:
        - name: get-coordinator-config
          in: body
          required: true
          schema:
            $ref: "#/definitions/GetCoordinatorArgs"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/CoordinatorConfig"
        '500':
          description: Config not initialized successfully or others
          x-go-name: Failure
          schema:
            $ref: "#/definitions/Error"
  "/runtime/startup":
    get:
      summary: Startup probe
      description: Check pod startup probe
      tags:
        - runtime
      responses:
        "200":
          description: Success
        "500":
          description: Failed
  "/runtime/readiness":
    get:
      summary: Readiness probe
      description: Check pod readiness probe
      tags:
        - runtime
      responses:
        "200":
          description: Success
        "500":
          description: Failed
  "/runtime/liveness":
    get:
      summary: Liveness probe
      description: Check pod liveness probe
      tags:
        - runtime
      responses:
        "200":
          description: Success
        "500":
          description: Failed

definitions:
  Error:
    description: API error
    type: string
  IpamAddArgs:
    description: IPAM request args
    type: object
    properties:
      containerID:
        type: string
      ifName:
        type: string
      netNamespace:
        type: string
      podNamespace:
        type: string
      podName:
        type: string
      podUID:
        type: string
      defaultIPv4IPPool:
        type: array
        items:
          type: string
      defaultIPv6IPPool:
        type: array
        items:
          type: string
      cleanGateway:
        type: boolean
    required:
      - containerID
      - ifName
      - netNamespace
      - podNamespace
      - podName
      - podUID
  IpamAddResponse:
    description: IPAM assignment IPs information
    type: object
    properties:
      ips:
        type: array
        items:
          $ref: "#/definitions/IpConfig"
      routes:
        type: array
        items:
          $ref: "#/definitions/Route"
      dns:
        type: object
        $ref: "#/definitions/DNS"
    required:
      - ips
  IpamDelArgs:
    description: IPAM release IP information
    type: object
    properties:
      containerID:
        type: string
      ifName:
        type: string
      netNamespace:
        type: string
      podNamespace:
        type: string
      podName:
        type: string
      podUID:
        type: string
    required:
      - containerID
      - ifName
      - podNamespace
      - podName
      - podUID
  DNS:
    description: IPAM CNI types DNS
    type: object
    properties:
      domain:
        type: string
      nameservers:
        type: array
        items:
          type: string
      options:
        type: array
        items:
          type: string
      search:
        type: array
        items:
          type: string
  Route:
    description: IPAM CNI types Route
    type: object
    properties:
      ifName:
        type: string
      dst:
        type: string
      gw:
        type: string
    required:
      - ifName
      - dst
      - gw
  IpConfig:
    description: IPAM IPs struct, contains ifName, Address and Gateway
    type: object
    properties:
      version:
        type: integer
        enum:
          - 4
          - 6
      address:
        type: string
      ipPool:
        type: string
      gateway:
        type: string
      nic:
        type: string
      vlan:
        type: integer
    required:
      - version
      - address
      - nic
  CoordinatorConfig:
    description: Coordinator config
    type: object
    properties:
      mode:
        type: string
      overlayPodCIDR:
        type: array
        items:
          type: string
      serviceCIDR:
        type: array
        items:
          type: string
      hijackCIDR:
        type: array
        items:
          type: string
      podMACPrefix:
        type: string
      tunePodRoutes:
        type: boolean
      podDefaultRouteNIC:
        type: string
      hostRuleTable:
        type: integer
      podRPFilter:
        type: integer
      detectIPConflict:
        type: boolean
      detectGateway:
        type: boolean
    required:
      - overlayPodCIDR
      - serviceCIDR
      - mode
      - tunePodRoutes
  GetCoordinatorArgs:
    description: Get Coordinator Args
    type: object
    properties:
      podName:
        type: string
      podNamespace:
        type: string
