swagger: "2.0"
info:
  description: Spiderpool Agent
  title: Spiderpool-Agent API
  version: v1
x-schemes:
  - unix
basePath: "/v1"
produces:
  - application/json
consumes:
  - application/json
paths:
  "/ipam/healthy":
    get:
      summary: Get health of spiderpool daemon
      description: |
        Check spiderpool daemonset health to make sure whether it's ready
        for CNI plugin usage
      tags:
        - connectivity
      responses:
        "200":
          description: Success
        "500":
          description: Failed
  "/ipam/ip":
    post:
      summary: Get ip from spiderpool daemon
      description: |
        Send a request to daemonset to ask for an ip assignment
      tags:
        - daemonset
      parameters:
        - name: ipam-add-args
          in: body
          required: true
          schema:
            $ref: "#/definitions/IpamAddArgs"
      responses:
        "200":
          description: Success
          schema:
            "$ref": "#/definitions/IpamAddResponse"
        "500":
          description: Internal server error
        "512":
          description: Wrong input information
        "513":
          description: Not allocatable pod
        "514":
          description: No available IP pool
        "515":
          description: All IP used out
    delete:
      summary: Delete ip from spiderpool daemon
      description: |
        Send a request to daemonset to ask for an ip deleting
      tags:
        - daemonset
      parameters:
        - name: ipam-del-args
          in: body
          required: true
          schema:
            $ref: "#/definitions/IpamDelArgs"
      responses:
        "200":
          description: Success
        "500":
          description: Failed
  /ipam/ips:
    post:
      summary: Assign multiple ip as a batch
      description: |
        Assign multiple ip for a pod, case for spiderflat compent
      tags:
        - daemonset
      responses:
        "200":
          description: Success
        "500":
          description: Allocation failure
    delete:
      summary: Delete multiple ip as a batch
      description: |
        Delete multiple ip for a pod, case for spiderflat compent
      tags:
        - daemonset
      responses:
        "200":
          description: Success
        "500":
          description: Failed
  /workloadendpoint:
    get:
      summary: Get workloadendpoint status
      description: |
        Get workloadendpoint details for spiderflat use
      tags:
        - daemonset
      responses:
        "200":
          description: Success
        "500":
          description: Get workloadendpoint failure
  "/runtime/startup":
    get:
      summary: Startup probe
      description: Check pod startup probe
      tags:
        - runtime
      responses:
        "200":
          description: Success
        "500":
          description: Failed
  "/runtime/readiness":
    get:
      summary: Readiness probe
      description: Check pod readiness probe
      tags:
        - runtime
      responses:
        "200":
          description: Success
        "500":
          description: Failed
  "/runtime/liveness":
    get:
      summary: Liveness probe
      description: Check pod liveness probe
      tags:
        - runtime
      responses:
        "200":
          description: Success
        "500":
          description: Failed
definitions:
  IpamAddArgs:
    description: IPAM request args
    type: object
    properties:
      podNamespace:
        type: string
      podName:
        type: string
      containerID:
        type: string
      ifName:
        type: string
      netNamespace:
        type: string
    required:
      - podNamespace
      - podName
      - containerID
      - ifName
      - netNamespace
  IpamAddResponse:
    description: IPAM assignment IPs information
    type: object
    properties:
      ips:
        type: array
        items:
          $ref: "#/definitions/IpConfig"
      routes:
        type: array
        items:
          $ref: "#/definitions/Route"
      dns:
        type: object
        $ref: "#/definitions/DNS"
    required:
      - ips
  IpamDelArgs:
    description: IPAM release IP information
    type: object
    properties:
      containerID:
        type: string
      ifName:
        type: string
      podNamespace:
        type: string
      podName:
        type: string
      netNamespace:
        type: string
    required:
      - containerID
      - ifName
      - podNamespace
      - podName
  DNS:
    description: IPAM CNI types DNS
    type: object
    properties:
      domain:
        type: string
      nameservers:
        type: array
        items:
          type: string
      options:
        type: array
        items:
          type: string
      search:
        type: array
        items:
          type: string
  Route:
    description: IPAM CNI types Route
    type: object
    properties:
      dst:
        type: string
      gw:
        type: string
    required:
      - dst
      - gw
  IpConfig:
    description: IPAM IPs struct, contains ifName, Address and Gateway
    type: object
    properties:
      version:
        type: integer
        enum:
          - 4
          - 6
      address:
        type: string
      gateway:
        type: string
      nic:
        type: string
      vlan:
        type: integer
    required:
      - version
      - address
      - nic
