---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: (unknown)
  name: spidermultusconfigs.spiderpool.spidernet.io
spec:
  group: spiderpool.spidernet.io
  names:
    categories:
    - spiderpool
    kind: SpiderMultusConfig
    listKind: SpiderMultusConfigList
    plural: spidermultusconfigs
    shortNames:
    - smc
    singular: spidermultusconfig
  scope: Namespaced
  versions:
  - name: v2beta1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Spec is the specification of the MultusCNIConfig
            properties:
              cniType:
                default: custom
                enum:
                - macvlan
                - ipvlan
                - sriov
                - ovs
                - ib-sriov
                - ipoib
                - custom
                type: string
              coordinator:
                description: CoordinationSpec defines the desired state of SpiderCoordinator.
                properties:
                  detectGateway:
                    default: false
                    description: DetectGateway to detect the gateway for the pod
                    type: boolean
                  detectIPConflict:
                    default: false
                    description: DetectIPConflict to detect the ip conflict for the
                      pod
                    type: boolean
                  hijackCIDR:
                    description: HijackCIDR configure static routing tables in the
                      pod that target these subnets to ensure that when the pod accesses
                      these subnets, packets are forwarded through the host network
                      stack, such as nodelocaldns(169.254.0.0/16)
                    items:
                      type: string
                    type: array
                  hostRPFilter:
                    default: 0
                    description: 'HostRPFilter is used for coordiantor to help set
                      the rp_filter parameters of the node. NOTE: This field is considered
                      deprecated in the future. the rp_filter of the node should be
                      configured by spiderpool-agent rather than coordinator plugin.
                      Configurable values: <negative number>/0/1/2, -1 means leave
                      it as it is. the default value is 0.'
                    type: integer
                  hostRuleTable:
                    default: 500
                    description: HostRuleTable specifies the table number of the routing
                      table used to configure the communication between the pod and
                      the local node.
                    type: integer
                  mode:
                    default: auto
                    description: Mode mode specifies the mode in which the coordinator
                      runs, and the configurable values include auto (default), underlay,
                      overlay, disabled.
                    enum:
                    - auto
                    - underlay
                    - overlay
                    - disabled
                    type: string
                  podCIDRType:
                    description: CoordinatorSpec is used by SpiderCoordinator and
                      SpiderMultusConfig in spidermultusconfig CRD , podCIDRType should
                      not be required, which could be merged from SpiderCoordinator
                      CR but in SpiderCoordinator CRD, podCIDRType should be required
                    enum:
                    - auto
                    - cluster
                    - calico
                    - cilium
                    - none
                    type: string
                  podDefaultRouteNIC:
                    description: PodDefaultRouteNIC PodDefaultRouteNIC is used to
                      configure the NIC where the pod's default route resides. the
                      default value is empty, which means the default route will remain
                      at eth0.
                    type: string
                  podMACPrefix:
                    description: 'PodMACPrefix the fixed MAC address prefix, the length
                      is two bytes. the lowest bit of the first byte must be 0, which
                      indicates the unicast MAC address. example: 0a:1b'
                    type: string
                  podRPFilter:
                    default: 0
                    description: 'PodRPFilter is used for coordiantor to help set
                      the rp_filter parameters of the pod. Configurable values: <negative
                      number>/0/1/2. negative number means leave it as it is. the
                      default value is 0.'
                    type: integer
                  tunePodRoutes:
                    default: true
                    description: TunePodRoutes specifies whether to tune pod routes
                      of multiple NICs on pods.
                    type: boolean
                  txQueueLen:
                    default: 0
                    description: TxQueueLen to set the tx_queue_len of the pod. requirement
                      is a positive integer the default value is 0, which means leaving
                      it as it is.
                    type: integer
                type: object
              customCNI:
                description: OtherCniTypeConfig only used for CniType custom, valid
                  json format, can be empty
                type: string
              disableIPAM:
                default: false
                type: boolean
              enableCoordinator:
                default: true
                description: if CniType was set to custom, we'll mutate this field
                  to be false
                type: boolean
              ibsriov:
                properties:
                  ibKubernetesEnabled:
                    default: false
                    type: boolean
                  ippools:
                    description: SpiderpoolPools could specify the IPAM spiderpool
                      CNI configuration default IPv4&IPv6 pools.
                    properties:
                      ipv4:
                        items:
                          type: string
                        type: array
                      ipv6:
                        items:
                          type: string
                        type: array
                    type: object
                  linkState:
                    default: enable
                    enum:
                    - auto
                    - enable
                    - disable
                    type: string
                  pkey:
                    type: string
                  rdmaIsolation:
                    default: true
                    type: boolean
                  resourceName:
                    type: string
                required:
                - resourceName
                type: object
              ipoib:
                properties:
                  ippools:
                    description: SpiderpoolPools could specify the IPAM spiderpool
                      CNI configuration default IPv4&IPv6 pools.
                    properties:
                      ipv4:
                        items:
                          type: string
                        type: array
                      ipv6:
                        items:
                          type: string
                        type: array
                    type: object
                  master:
                    type: string
                type: object
              ipvlan:
                properties:
                  bond:
                    properties:
                      mode:
                        format: int32
                        maximum: 6
                        minimum: 0
                        type: integer
                      name:
                        type: string
                      options:
                        type: string
                    required:
                    - mode
                    - name
                    type: object
                  ippools:
                    description: SpiderpoolPools could specify the IPAM spiderpool
                      CNI configuration default IPv4&IPv6 pools.
                    properties:
                      ipv4:
                        items:
                          type: string
                        type: array
                      ipv6:
                        items:
                          type: string
                        type: array
                    type: object
                  master:
                    items:
                      type: string
                    type: array
                  vlanID:
                    format: int32
                    maximum: 4094
                    minimum: 0
                    type: integer
                required:
                - master
                type: object
              macvlan:
                properties:
                  bond:
                    properties:
                      mode:
                        format: int32
                        maximum: 6
                        minimum: 0
                        type: integer
                      name:
                        type: string
                      options:
                        type: string
                    required:
                    - mode
                    - name
                    type: object
                  ippools:
                    description: SpiderpoolPools could specify the IPAM spiderpool
                      CNI configuration default IPv4&IPv6 pools.
                    properties:
                      ipv4:
                        items:
                          type: string
                        type: array
                      ipv6:
                        items:
                          type: string
                        type: array
                    type: object
                  master:
                    items:
                      type: string
                    type: array
                  vlanID:
                    format: int32
                    maximum: 4094
                    minimum: 0
                    type: integer
                required:
                - master
                type: object
              ovs:
                properties:
                  bridge:
                    type: string
                  deviceID:
                    description: PCI address of a VF in valid sysfs format
                    type: string
                  ippools:
                    description: SpiderpoolPools could specify the IPAM spiderpool
                      CNI configuration default IPv4&IPv6 pools.
                    properties:
                      ipv4:
                        items:
                          type: string
                        type: array
                      ipv6:
                        items:
                          type: string
                        type: array
                    type: object
                  trunk:
                    items:
                      properties:
                        id:
                          maximum: 4094
                          minimum: 0
                          type: integer
                        maxID:
                          maximum: 4094
                          minimum: 0
                          type: integer
                        minID:
                          maximum: 4094
                          minimum: 0
                          type: integer
                      type: object
                    type: array
                  vlan:
                    format: int32
                    type: integer
                required:
                - bridge
                type: object
              sriov:
                properties:
                  enableRdma:
                    default: false
                    type: boolean
                  ippools:
                    description: SpiderpoolPools could specify the IPAM spiderpool
                      CNI configuration default IPv4&IPv6 pools.
                    properties:
                      ipv4:
                        items:
                          type: string
                        type: array
                      ipv6:
                        items:
                          type: string
                        type: array
                    type: object
                  maxTxRateMbps:
                    minimum: 0
                    type: integer
                  minTxRateMbps:
                    minimum: 0
                    type: integer
                  resourceName:
                    type: string
                  vlanID:
                    format: int32
                    maximum: 4094
                    minimum: 0
                    type: integer
                required:
                - resourceName
                type: object
            type: object
        type: object
    served: true
    storage: true
