---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: (unknown)
  name: spiderendpoints.spiderpool.spidernet.io
spec:
  group: spiderpool.spidernet.io
  names:
    categories:
    - spiderpool
    kind: SpiderEndpoint
    listKind: SpiderEndpointList
    plural: spiderendpoints
    shortNames:
    - se
    singular: spiderendpoint
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: interface
      jsonPath: .status.current.ips[0].interface
      name: INTERFACE
      type: string
    - description: ipv4Pool
      jsonPath: .status.current.ips[0].ipv4Pool
      name: IPV4POOL
      type: string
    - description: ipv4
      jsonPath: .status.current.ips[0].ipv4
      name: IPV4
      type: string
    - description: ipv6Pool
      jsonPath: .status.current.ips[0].ipv6Pool
      name: IPV6POOL
      type: string
    - description: ipv6
      jsonPath: .status.current.ips[0].ipv6
      name: IPV6
      type: string
    - description: node
      jsonPath: .status.current.node
      name: NODE
      type: string
    name: v2beta1
    schema:
      openAPIV3Schema:
        description: Spiderndpoint is the Schema for the spiderendpoints API.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          status:
            description: WorkloadEndpointStatus defines the observed state of SpiderEndpoint.
            properties:
              current:
                properties:
                  ips:
                    items:
                      properties:
                        cleanGateway:
                          type: boolean
                        interface:
                          type: string
                        ipv4:
                          type: string
                        ipv4Gateway:
                          type: string
                        ipv4Pool:
                          type: string
                        ipv6:
                          type: string
                        ipv6Gateway:
                          type: string
                        ipv6Pool:
                          type: string
                        routes:
                          items:
                            properties:
                              dst:
                                type: string
                              gw:
                                type: string
                            required:
                            - dst
                            - gw
                            type: object
                          type: array
                        vlan:
                          default: 0
                          description: 'DEPRECATED: Vlan is deprecated.'
                          format: int64
                          maximum: 4094
                          minimum: 0
                          type: integer
                      required:
                      - interface
                      type: object
                    type: array
                  node:
                    type: string
                  uid:
                    type: string
                required:
                - ips
                - node
                - uid
                type: object
              ownerControllerName:
                type: string
              ownerControllerType:
                type: string
            required:
            - current
            - ownerControllerName
            - ownerControllerType
            type: object
        type: object
    served: true
    storage: true
    subresources: {}
