---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: ""
  creationTimestamp: null
  name: spidersubnets.spiderpool.spidernet.io
spec:
  group: spiderpool.spidernet.io
  names:
    categories:
    - spiderpool
    kind: SpiderSubnet
    listKind: SpiderSubnetList
    plural: spidersubnets
    shortNames:
    - ss
    singular: spidersubnet
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - description: ipVersion
      jsonPath: .spec.ipVersion
      name: VERSION
      type: string
    - description: subnet
      jsonPath: .spec.subnet
      name: SUBNET
      type: string
    - description: freeIPCount
      jsonPath: .status.freeIPCount
      name: FREE-IP-COUNT
      type: integer
    - description: totalIPCount
      jsonPath: .status.totalIPCount
      name: TOTAL-IP-COUNT
      type: integer
    name: v1
    schema:
      openAPIV3Schema:
        description: SpiderSubnet is the Schema for the spidersubnets API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: SubnetSpec defines the desired state of SpiderSubnet
            properties:
              excludeIPs:
                items:
                  type: string
                type: array
              gateway:
                type: string
              ipVersion:
                enum:
                - 4
                - 6
                format: int64
                type: integer
              ips:
                items:
                  type: string
                minItems: 1
                type: array
              routes:
                items:
                  properties:
                    dst:
                      type: string
                    gw:
                      type: string
                  required:
                  - dst
                  - gw
                  type: object
                type: array
              subnet:
                type: string
              vlan:
                default: 0
                format: int64
                maximum: 4095
                minimum: 0
                type: integer
            required:
            - ips
            - subnet
            type: object
          status:
            description: SubnetStatus defines the observed state of SpiderSubnet
            properties:
              freeIPCount:
                format: int64
                minimum: 0
                type: integer
              freeIPs:
                items:
                  type: string
                type: array
              totalIPCount:
                format: int64
                minimum: 0
                type: integer
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
