site_name: spiderpool
docs_dir: docs
site_dir: site
repo_name: spidernet-io/spiderpool
repo_url: https://github.com/spidernet-io/spiderpool
remote_branch: github_pages
theme:
  name: readthedocs
  # The maximum depth of the navigation tree in the sidebar
  navigation_depth: 2
  palette:
    scheme: default
  features:
    - navigation.instant
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest
    - search.share

plugins:
  - tags
  - search

markdown_extensions:
  - meta
  - toc
  - tables
  - fenced_code
  - tables
  - attr_list

nav:
  - README.md
  - Usage:
      - usage/basic.md
      - usage/install.md
      - usage/basic.md
      - usage/ippool-multi.md
      - usage/ippool-namespace.md
      - usage/ippool-affinity-namespace.md
      - usage/ippool-affinity-node.md
      - usage/ippool-affinity-pod.md
      - usage/ipv6.md
      - usage/multi-interfaces-annotation.md
      - usage/multi-interfaces-cni.md
      - usage/statefulset.md
      - usage/reserved-ip.md
      - usage/spider-subnet.md
      - usage/debug.md
      - usage/third-party-controller.md
  - Concepts:
      - concepts/arch.md
      - concepts/allocation.md
      - concepts/gc.md
      - concepts/annotation.md
      - concepts/config.md
      - concepts/metrics.md
      - concepts/spiderippool.md
      - concepts/spiderreservedip.md
      - concepts/spiderendpoint.md
      - concepts/spidersubnet.md
  - Reference:
      - cmdref/spiderpoolctl.md
      - cmdref/spiderpool-controller.md
      - cmdref/spiderpool-agent.md
  - Development:
      - develop/roadmap.md
      - develop/pullrequest.md
      - develop/release.md
      - develop/swagger_openapi.md
      - develop/test.md
      - develop/changelog.md
      - develop/upgrade.md
