name: Call Update githubpages

on:
  workflow_call:
    inputs:
      site_artifact_name:
        required: true
        type: string
      chart_artifact_name:
        required: true
        type: string

permissions: write-all

env:
  MERGE_BRANCH: github_pages
  DEST_DIRECTORY: 'docs'
  PR_LABEL: pr/release/robot_update_githubpage
  PR_REVIWER: weizhoublue

jobs:
  create_pr:
    name: Create PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ env.MERGE_BRANCH }}

      - name: Get Base Chart URL
        id: get_base_url
        run: |
          name=${{ github.repository }}
          proj=${name#*/}
          url=https://${{ github.repository_owner }}.github.io/${proj}
          echo "url=${url}" >> $GITHUB_ENV

      - name: Prepare Directory
        run: |
          rm -rf _oldCharts
          cp -rf ${{ env.DEST_DIRECTORY }}/charts _oldCharts
          rm -rf ${{ env.DEST_DIRECTORY }}
          mkdir ${{ env.DEST_DIRECTORY }}
          mkdir ${{ env.DEST_DIRECTORY }}/charts

      - name: Download Website Artifact
        uses: actions/download-artifact@v6.0.0
        with:
          name: ${{ inputs.site_artifact_name }}
          path: ${{ env.DEST_DIRECTORY }}

      - name: Download Chart Artifact
        uses: actions/download-artifact@v6.0.0
        with:
          name: ${{ inputs.chart_artifact_name }}
          path: ${{ env.DEST_DIRECTORY }}/charts

      - name: Untar Artifact
        run: |
          # untar website html
          cd ${{ env.DEST_DIRECTORY }}
          ALL_TAR_FILE=`ls *.tar.gz`
          for ITEM in $ALL_TAR_FILE ; do
            echo "untar $ITEM "
            tar -xzvf $ITEM
            rm -f $ITEM
          done
          # restore old charts
          cd ..
          # do not overwrite new chart tar
          cp -n _oldCharts/* ${{ env.DEST_DIRECTORY }}/charts
          rm -rf _oldCharts
          # prepare charts index.yaml
          cd ${{ env.DEST_DIRECTORY }}
          helm repo index  ./charts  --url ${{ env.url }}/charts
          mv ./charts/index.yaml ./index.yaml

      - uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      # ========= finally, create PR
      # Allow auto-merge on general
      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v7.0.8
        with:
          title: "robot update chart and website from ${{ needs.prepare_doc.outputs.ref }} to branch ${{ env.MERGE_BRANCH }} "
          commit-message: "robot update chart and website from ${{ needs.prepare_doc.outputs.ref }} to branch ${{ env.MERGE_BRANCH }} "
          branch-suffix: timestamp
          branch: robot/update_doc
          committer: weizhoublue<weizhou.lan@daocloud.io>
          delete-branch: true
          base: ${{ env.MERGE_BRANCH }}
          signoff: true
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: ${{ env.PR_LABEL }}
