#name: Chatgtp Code Review

#permissions: write-all

#on:
#  pull_request:
#    types: [opened, reopened, synchronize]
#    paths:
#      - '**.go'
#      - '**.sh'

#jobs:
#  test:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: anc95/ChatGPT-CodeReview@main
#        env:
#          GITHUB_TOKEN: ${{ secrets.WELAN_PAT }}
#          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
#          MODEL:
#          top_p: 1
#          temperature: 1
