# cleaner for ghcr image , each day
# NOTE: at now only orgs is supported , for personal it fail
name: GC Image CI Each day

env:
  ONLINE_REGISTER: ghcr.io

on:
  schedule:
    # Run the GC at 3am each day
    - cron: "0 3 * * *"

jobs:
  purge-image:
    name: Delete image from ghcr.io
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: spiderpool-agent
          - name: spiderpool-controller

    steps:
      - name: Delete CI image
        uses: vlaurin/action-ghcr-prune@v0.4.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          organization: ${{ github.repository_owner }}
          container: ${{ env.ONLINE_REGISTER }}/${{ github.repository }}/${{ matrix.name }}-ci
          dry-run: false # Dry-run first, then change to `false`
          # Minimum age in days of a version before it is pruned. Defaults to 0 which matches all versions of a container
          # longer than 1 days, will gc it
          older-than: 1 # days
          # Count of most recent, matching containers to exclude from pruning
          keep-last: 0
          #untagged versions should be pruned
          untagged: true
          # if no tag-regex , all tag will be pruned
          tag-regex: ${{ steps.tag.outputs.tag }}*