name: Auto Document Lint

on:
  push:
    branches:
      - main
      - release-*
    paths:
      - "docs/**"
  pull_request:
    branches:
      - main
      - release-*
    paths:
      - "docs/**"
  # checkout all markdown
  workflow_dispatch:
    inputs:
      ref:
        description: "branch, tag"
        required: true
        default: main

jobs:
  link-check:
    name: Doc Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: Checkout
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: actions/checkout@v4

      - name: Check documents
        run: |
            make check_doc
