# generating changelog to directory /changelogs/*** of main branch
# when tag or dispatch by manual , auto generate changelog by the related-label history PR between tags,
# then commit the pr to main branch , then auto approve it
# commit changelog: changelogs/CHANGELOG-{begin_tag}-to-{end_tag}.md
name: Update Changelog By Hand

on:
#  push:
#    tags:
#      - v[0-9]+.[0-9]+.[0-9]+
#      - v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+
  # called by build release image
  workflow_call:
  # call by manual
  # if from_tag and to_tag is empty, pase latest tag auto
  workflow_dispatch:
    inputs:
      from_tag:
        description: 'from_tag: start commit based on which tag'
        required: true
        default: v1.0.0
      to_tag:
        description: 'to_tag: last commit based on which tag'
        required: true
        default: v1.0.0

env:
  CHANGELOG_DIR: changelogs
  MERGE_TO_BRANCH: main
  PR_LABEL: pr/release/robot_changelog
  PR_REVIWER: weizhoublue
  CHANGELOG_CONF: .github/changelog_builder_conf.json
  CHANGELOG_RESULT_DIR: changelogs
  CHANGELOG_TEMP_FILE: _temp_changelog

jobs:
  generate_changelog:
    name: auto generate release changelog
    runs-on: ubuntu-latest
    steps:

      # checkout code for tag and pr
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Only a single commit is fetched by default, for the ref/SHA that triggered the workflow
          # if Set fetch-depth: 0 to fetch all history for all branches and tags
          fetch-depth: 0



      - name: Check Tag
        id: check_tag
        continue-on-error: false
        run: |
          if ${{ github.event_name != 'workflow_dispatch' }} ; then
              echo "auto tag for tag event"
              echo ::set-output name=auto_tag::true
              exit 0
          fi
          if [ -z "${{ github.event.inputs.to_tag }}" ] && [ -z "${{ github.event.inputs.from_tag }}" ] ; then
              echo "auto tag for dispatch event"
              echo ::set-output name=auto_tag::true
              exit 0
          fi
          if [ -n "${{ github.event.inputs.to_tag }}" ] && [ -n "${{ github.event.inputs.from_tag }}" ] ; then
              echo "begin to validate tags"
          else
              echo "from_tag and to_tag should be fill , or empty at same time"
              exit 1
          fi
          if ! git describe --tags --abbrev=0  ${{ github.event.inputs.from_tag }} &>/dev/null ; then
              echo "error, does not exist from_tag ${{ github.event.inputs.from_tag }} "
              exit 1
          else
              echo "exist from_tag ${{ github.event.inputs.from_tag }} "
          fi
          if ! git describe --tags --abbrev=0  ${{ github.event.inputs.to_tag }} &>/dev/null ; then
              echo "error, does not exist to_tag ${{ github.event.inputs.to_tag }} "
              exit 2
          else
              echo "exist to_tag ${{ github.event.inputs.to_tag }} "
          fi
          echo ::set-output name=auto_tag::false

      # specify the tag
      - name: Build Changelog By Manual Tag
        id: create_changelog_by_manul_tag
        if: ${{ steps.check_tag.outputs.auto_tag == 'false' }}
        uses: mikepenz/release-changelog-builder-action@v2.9.0
        with:
          configuration: ${{ env.CHANGELOG_CONF }}
          outputFile: ./_temp_changelog
          fromTag: ${{ github.event.inputs.from_tag }}
          toTag: ${{ github.event.inputs.to_tag }}
          failOnError: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/mikepenz/release-changelog-builder-action
      # PRs will only show up in the changelog if assigned one of the default label categories "feature", "fix" or "test" . Or else, we should configure yaml
      # auto parse the latest tag and previous one
      - name: Build Changelog By Auto Tag
        id: create_changelog_by_auto_tag
        if: ${{ steps.check_tag.outputs.auto_tag == 'true' }}
        uses: mikepenz/release-changelog-builder-action@v2.9.0
        with:
          configuration: ${{ env.CHANGELOG_CONF }}
          outputFile: ./_temp_changelog
          failOnError: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Changelog File
        id: generate_changelog_file
        continue-on-error: false
        if: steps.create_changelog_by_auto_tag.outputs.failed == 'false' ||  steps.create_changelog_by_manul_tag.outputs.failed == 'false'
        run: |
          if [ ! -f "_temp_changelog" ] ; then
               echo "failed to find auto-generated changelog result file $TEMP_FILE"
               exit 1
          fi
          if ${{ steps.create_changelog_by_auto_tag.outputs.failed == 'false' }} ; then
              CHANGELOG_FILE_NAME=${{ steps.create_changelog_by_auto_tag.outputs.fromTag }}-to-${{ steps.create_changelog_by_auto_tag.outputs.toTag }}.md
          else
              CHANGELOG_FILE_NAME=${{ steps.create_changelog_by_manul_tag.outputs.fromTag }}-to-${{ steps.create_changelog_by_manul_tag.outputs.toTag }}.md          
          fi
          echo ::set-output name=changelog_path::${CHANGELOG_FILE_NAME}
          mv  _temp_changelog  ${CHANGELOG_FILE_NAME}
          cat ${CHANGELOG_FILE_NAME}

      - name: Upload Changelog
        uses: actions/upload-artifact@v3.0.0
        with:
          name: changelog-result
          path: ${{ steps.generate_changelog_file.outputs.changelog_path }}
          retention-days: 1
          if-no-files-found: error

  # mikepenz/release-changelog-builder-action maybe checkout to the tag who is not latest HEAD of main branch ,
  # which make fail to peter-evans/create-pull-request. So we do it in another job
  create_pr:
    name: create pr
    runs-on: ubuntu-latest
    needs: [generate_changelog]
    steps:
      - name: Check Tag
        id: check_tag
        run: |
          if ${{ github.event_name == 'workflow_dispatch' }} ; then
              echo ::set-output name=tag::${{ github.event.inputs.to_tag }}
          else
              echo ::set-output name=tag::${GITHUB_REF##*/}
          fi

      # checkout out to an online branch/tag who is not the destination merged branch
      #      of action peter-evans/create-pull-request, or else PR fail
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          clean: true
          ref: ${{ steps.check_tag.outputs.tag }}

      - name: Download Changelog
        uses: actions/download-artifact@v3.0.0
        with:
          name: changelog-result
          path: .tmp/

      - name: Move File
        id: move_file
        continue-on-error: false
        run: |
          FILE_NAME=$( ls .tmp/ )
          ls .tmp/
          echo $FILE_NAME
          TITLE=${FILE_NAME%%.md}
          echo $TITLE
          mv .tmp/${FILE_NAME}  ${{ env.CHANGELOG_RESULT_DIR }}/CHANGELOG-${FILE_NAME}
          echo ::set-output name=title::${TITLE}
          rm -rf .tmp/
          git branch -a
          git status

      # !!! the current local source branch and destination branch must exist online , or else fail to pr
      # based on local branch who must exist online , the action commit all modified file and commit to New branch
      # finally merge to destination branch who must exist online
      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v4
        with:
          title: "robot Update Changelog ${{ steps.move_file.outputs.title }}"
          # from branch
          commit-message: "robot update Changelog ${{ steps.move_file.outputs.title }} "
          # branch name: ${branch}-${branch-suffix}
          # an branch suffix could make sure the branch is unique
          branch-suffix: timestamp
          branch: update_changelog
          # Delete the branch when closing pull requests, and when undeleted after merging
          delete-branch: true
          # merge to
          base: ${{ env.MERGE_TO_BRANCH }}
          signoff: true
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: ${{ env.PR_LABEL }}
          reviewers: ${{ env.PR_REVIWER }}

      - name: Check PR Outputs
        if: ${{ steps.create_pr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.create_pr.outputs.pr_number }}"
          echo "Pull Request URL - ${{ steps.create_pr.outputs.pr_url }}"


