name: Scan Image

on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string
      ref:
        required: false
        type: string
      push:
        required: false
        type: boolean

jobs:
  trivy_scan_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          ref: ${{ inputs.ref }}

      - name: Download spiderpool-agent image
        uses: actions/download-artifact@v4.1.8
        with:
          name: image-tar-spiderpool-agent
          path: test/.download

      - name: Download spiderpool-controller image
        uses: actions/download-artifact@v4.1.8
        with:
          name: image-tar-spiderpool-controller
          path: test/.download

      - name: List downloaded files
        run: ls -al test/.download

      # https://github.com/aquasecurity/trivy-action/issues/389
      - name: load and scan spiderpool-agent image
        uses: aquasecurity/trivy-action@0.29.0
        env:
          TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db,ghcr.io/aquasecurity/trivy-db
        with:
          input: test/.download/spiderpool-agent-race.tar
          severity: 'CRITICAL,HIGH'

      - name: load and scan spiderpool-controller image
        uses: aquasecurity/trivy-action@0.29.0
        env:
          TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db,ghcr.io/aquasecurity/trivy-db
        with:
          input: test/.download/spiderpool-controller-race.tar
          severity: 'CRITICAL,HIGH'
